name: Moedb

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: build moedb-server
      run: |
          cd nijika
          go mod download
          CGO_ENABLED=1 go build -o moedb-server

    - name: Upload binary artifacts to next stage
      uses: actions/upload-artifact@v2
      with:
        name: binary-file
        path: ./nijika/moedb-server

    - name: Upload systemd artifacts to next stage
      uses: actions/upload-artifact@v2
      with:
        name: systemd
        path: ./nijika/etc/moedb-server.service
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: download binary artifacts
      uses: actions/download-artifact@v2
      with:
        name: binary-file

    - name: download systemd artifacts
      uses: actions/download-artifact@v2
      with:
        name: systemd

    - name: upload artifacts to server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "moedb-server.service,moedb-server"
        target: "~/moedb" 
    
    - name: restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
                systemctl restart moedb-server.service
